// IRIS Gaze Tracking Library - C FFI Header
// Auto-generated by cbindgen - DO NOT EDIT
//
// This header provides the C interface to the Rust gaze tracking library.
// Include this in your Swift bridging header or use with a module map.


#ifndef IRIS_GAZE_H
#define IRIS_GAZE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * MediaPipe landmark indices
 */
#define FaceLandmarks_NOSE_TIP 4

#define FaceLandmarks_FOREHEAD 10

#define FaceLandmarks_LEFT_EYE_TOP 159

#define FaceLandmarks_LEFT_EYE_BOTTOM 145

#define FaceLandmarks_LEFT_EYE_LEFT 33

#define FaceLandmarks_LEFT_EYE_RIGHT 133

#define FaceLandmarks_RIGHT_EYE_TOP 386

#define FaceLandmarks_RIGHT_EYE_BOTTOM 374

#define FaceLandmarks_RIGHT_EYE_LEFT 362

#define FaceLandmarks_RIGHT_EYE_RIGHT 263

/**
 * Error codes returned by the library
 */
typedef enum GazeError {
  /**
   * No error
   */
  None = 0,
  /**
   * Camera not found or failed to open
   */
  CameraError = 1,
  /**
   * Failed to load ML model
   */
  ModelError = 2,
  /**
   * No face detected in frame
   */
  NoFaceDetected = 3,
  /**
   * Invalid configuration
   */
  InvalidConfig = 4,
  /**
   * Internal error
   */
  InternalError = 5,
  /**
   * Tracker not initialized
   */
  NotInitialized = 6,
} GazeError;

/**
 * Status of the gaze tracker
 */
typedef enum TrackerStatus {
  /**
   * Tracker is not initialized
   */
  Uninitialized = 0,
  /**
   * Tracker is initializing (loading model, opening camera)
   */
  Initializing = 1,
  /**
   * Tracker is running and producing gaze data
   */
  Running = 2,
  /**
   * Tracker is paused
   */
  Paused = 3,
  /**
   * Tracker encountered an error
   */
  Error = 4,
  /**
   * Tracker is stopped
   */
  Stopped = 5,
} TrackerStatus;

/**
 * Main gaze tracker - mirrors Python implementation
 */
typedef struct GazeTracker GazeTracker;

/**
 * Result of a single gaze tracking frame
 */
typedef struct GazeResult {
  /**
   * X coordinate on screen (0 to screen_width)
   */
  double x;
  /**
   * Y coordinate on screen (0 to screen_height)
   */
  double y;
  /**
   * Event type: 0=none, 1=gaze, 2=blink/wink
   */
  uint8_t event_type;
  /**
   * Blink eye: 0=none, 1=left, 2=right, 3=both
   */
  uint8_t blink_eye;
  /**
   * Whether this result is valid
   */
  bool valid;
} GazeResult;


struct GazeTracker *iris_gaze_init(int32_t screen_width,
                                   int32_t screen_height,
                                   const char *_dominant_eye)
;

 struct GazeResult iris_gaze_get_frame(struct GazeTracker *tracker) ;

 enum TrackerStatus iris_gaze_get_status(const struct GazeTracker *tracker) ;

 enum GazeError iris_gaze_get_error(const struct GazeTracker *_tracker) ;

 void iris_gaze_stop(struct GazeTracker *tracker) ;

 void iris_gaze_destroy(struct GazeTracker *tracker) ;

 void iris_gaze_set_screen_size(struct GazeTracker *tracker, int32_t width, int32_t height) ;

 void iris_gaze_pause(struct GazeTracker *tracker) ;

 void iris_gaze_resume(struct GazeTracker *tracker) ;


void iris_gaze_set_calibration(struct GazeTracker *tracker,
                               double x_min,
                               double x_max,
                               double y_min,
                               double y_max)
;

 void iris_gaze_set_reach_gain(struct GazeTracker *_tracker, double _gain_x, double _gain_y) ;

 bool iris_gaze_get_raw_position(struct GazeTracker *_tracker, double *_nose_x, double *_nose_y) ;

 void iris_gaze_set_auto_calibrate(struct GazeTracker *_tracker, bool _enabled) ;

#endif  /* IRIS_GAZE_H */
